stages:
  - build
  - test

build_llvm6:
  stage: build
  image: luizperes/parabix:llvm-6.0.1
  script:
    - mkdir build && cd build
    - git clone https://github.com/Z3Prover/z3.git && cd z3 && python scripts/mk_make.py && cd build && make && make install && cd ../..
    - cmake -DCMAKE_BUILD_TYPE=Release ..
    - make -j4

.test-default: &test-default
  stage: test
  image: luizperes/parabix:llvm-6.0.1
  script:
    - mkdir -p build && cd build
    - git clone https://github.com/Z3Prover/z3.git && cd z3 && python scripts/mk_make.py && cd build && make && make install && cd ../..
    - cmake -DCMAKE_BUILD_TYPE=Release ..
    - make -j4 check && make kernel-tests

test_llvm6:
  <<: *test-default

merge_request_llvm6:
  <<: *test-default
  rules:
    # If there is a merge request
    - if: '$CI_MERGE_REQUEST_IID'

.test-avx-default: &test-avx-default
  stage: test
  script:
    - mkdir -p build && cd build
    # Make sure the runner has LLVM installed on /opt/llvm/libllvm{LLVM_VERSION}
    # LLVM 6 is currently the default LLVM on cs-osl-08
    - cmake -DCMAKE_BUILD_TYPE=Release ..
    - make -j4 check && make kernel-tests

test_avx2_llvm6:
  <<: *test-avx-default
  tags:
    - avx2

merge_request_avx2_llvm6:
  <<: *test-avx-default
  rules:
    # If there is a merge request
    - if: '$CI_MERGE_REQUEST_IID'
  tags:
    - avx2

test_avx512_llvm6:
  <<: *test-avx-default
  tags:
    - avx512

merge_request_avx512_llvm6:
  <<: *test-avx-default
  rules:
    # If there is a merge request
    - if: '$CI_MERGE_REQUEST_IID'
  tags:
    - avx512

