stages:
  - triggers

workflow:
  rules:
    # If `$FORCE_GITLAB_CI` is set, create a pipeline.
    - if: '$FORCE_GITLAB_CI'
    # For merge requests, create a pipeline.
    - if: '$CI_MERGE_REQUEST_IID'
    # For tags, create a pipeline.
    - if: '$CI_COMMIT_TAG'
    # If commit title starts with 'run-ci:'
    - if: '$CI_COMMIT_TITLE =~ /^(r|R)un-ci:/'

trigger_llvm5:
  stage: triggers
  trigger:
    include: .gitlab-pipelines/llvm5/config.yml
    strategy: depend

trigger_llvm6:
  stage: triggers
  trigger:
    include: .gitlab-pipelines/llvm6/config.yml
    strategy: depend

trigger_llvm7:
  stage: triggers
  trigger:
    include: .gitlab-pipelines/llvm7/config.yml
    strategy: depend

trigger_llvm8:
  stage: triggers
  trigger:
    include: .gitlab-pipelines/llvm8/config.yml
    strategy: depend

trigger_llvm9:
  stage: triggers
  trigger:
    include: .gitlab-pipelines/llvm9/config.yml
    strategy: depend

trigger_llvm10:
  stage: triggers
  trigger:
    include: .gitlab-pipelines/llvm10/config.yml
    strategy: depend

trigger_llvm11:
  stage: triggers
  trigger:
    include: .gitlab-pipelines/llvm11/config.yml
    strategy: depend
